version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: persys_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persys_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
      
  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - app_network

  app:
    build:
      context: .
      target: app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://persys_user:password@db:5432/persys_db"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://redis:6379"
      JOB_QUEUE_NAME: "persys_job_queue"
    ports:
      - "3000:3000"
    networks:
      - app_network
  worker:
    build:
      context: .
      target: worker
    command: npm run start:worker
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgresql://persys_user:password@db:5432/persys_db"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  redis_data: